#94 [ADD] bookmarked posts to Profile Schema
gaticosalas/SOEN341-IG-Clone pull request #102
Opened 2021-03-23 17:55 UTC by loren589

Array 'bookmarkedPosts' of post objects added to Profile Schema. Also includes the date the post was posted on.

2021-03-23 19:22 UTC, gaticosalas requested changes

2021-03-23 19:22 UTC, gaticosalas commented on models/Profile.js
> +        post: {
rename it to postID

2021-03-23 19:22 UTC, gaticosalas commented on models/Profile.js
> +        }
add a picture attribute to the boomarkedPosts object like this:
```
    picture:{
            type: String
    }
```

2021-03-23 19:37 UTC, gaticosalas approved these changes
good!

2021-03-29 21:35 UTC, vishybala approved these changes

2021-03-29 21:35 UTC, merged

2021-04-13 16:39 UTC, MKB-1 commented
user story: 4