#8 Registration form
gaticosalas/SOEN341-IG-Clone pull request #31
Opened 2021-02-14 06:11 UTC by Joshua-Castillo

Changes to App.js : added Link to Register form 
Changes to layout/components : added necessary components and routing for Register form

2021-02-14 16:26 UTC, gaticosalas requested changes
Register component was well done! just edit some of the other files to remove the class components.

2021-02-14 16:26 UTC, gaticosalas commented on client/src/App.js
> +import Register from './containers/layout/Register';
Reminder: We are not using class Components anymore so we will not be needing containers anymore!

2021-02-14 16:26 UTC, gaticosalas commented on client/src/App.js
> +          <Route exact path='/register' component={(props) => <Register {...props} Layout={RegisterComponent} title="Register" />} />
Since we are not using class components, the Route Component will just look like this:
<Route exact path='/register' component={RegisterComponent} />

2021-02-14 16:26 UTC, gaticosalas commented on client/src/App.js
> +          <Route exact path='/register' component={(props) => <Register {...props} Layout={RegisterComponent} title="Register" />} />
`<Route exact path='/register' component={RegisterComponent} />`

2021-02-14 16:26 UTC, gaticosalas commented on client/src/components/layout/home.jsx
>      document.title = title;
Home (or any other component actually) will not have the title prop anymore, so you can just leave it as
`const Home = () => {` for now and delete the document.title part

2021-02-14 16:26 UTC, gaticosalas commented on client/src/containers/layout/Register.js
> +export default Register;
We can delete this entire file. No more class components!

2021-02-15 00:01 UTC, gaticosalas requested changes
Caught another change that had to be done! See code comments for explanation

2021-02-15 00:01 UTC, gaticosalas commented on client/src/components/layout/register.jsx
> +                        />
"name" has been changed to "first_name" and "last_name" in the Database and we also added a "username" field so just add those fields instead of name also!

2021-02-16 17:39 UTC, closed without merging

2021-02-16 17:39 UTC, vishybala commented
Needs amends