#13 [ADD] Post Backend CRUD routes
gaticosalas/SOEN341-IG-Clone pull request #32
Opened 2021-02-14 13:59 UTC by loren589

Added all the backend routes related to the posts. I also added the post picture attribute to the post route, but I have some questions as to how picture files get uploaded to the database, which I'll ask in the meeting on Tuesday.

2021-02-14 16:43 UTC, gaticosalas requested changes
Great job, just a few little fixes!

2021-02-14 16:43 UTC, gaticosalas commented on routes/api/posts.js
> +    }
Text will not be necessary but picture will, so just change the check method to:
`check('picture', 'Picture is necessary').not().Empty()`.

2021-02-14 16:43 UTC, gaticosalas commented on routes/api/posts.js
> +            picture: req.body.string, //look into using Multer? It's a node.js middleware used to upload files to the DB
You're right about Multer! checking into it!

2021-02-14 16:43 UTC, gaticosalas commented on routes/api/posts.js
> +            text: req.body.text,
Reminder that you called the text 'caption' in your Schema, so rename this to caption too to stay consistent!

2021-02-15 22:12 UTC, gaticosalas approved these changes
Perfect!

2021-02-15 22:39 UTC, MKB-1 commented
Good Job!

2021-02-15 22:39 UTC, MKB-1 approved these changes

2021-02-15 22:46 UTC, merged